export const STATES = {
    HARVESTING_ENERGY : ' HARVESTING_ENERGY',
    DEPOSITING_ENERGY :'DEPOSITING_ENERGY',
    SEARCHING_ENERGY : 'SEARCHING_ENERGY ',
    LOOTING_ENERGY : 'LOOTING_ENERGY',
    PICKUP_ENERGY : 'PICKUP_ENERGY',
    UPGRADING_CONTROLLER : 'UPGRADING_CONTROLLER',
    BUILD_CONSTRUCTION : 'BUILD_CONSTRUCTION ',
    REPAIR_CONSTRUCTION : ' REPAIR_CONSTRUCTION '
}

export const STATUS = {
    ENERGY_STORAGE_FULL : 'ENERGY_STORAGE_FULL',
    ENERGY_STORAGE_EMPTY : 'ENERGY_STORAGE_EMPTY',
    ENERGY_NOT_FOUND : 'ENERGY_NOT_FOUND',
    CONSTRUCTIONS_NOT_FOUND : 'CONSTRUCTIONS_NOT_FOUND',
}



